# -*- coding: utf-8 -*-
"""apppdf.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrsMk96TEkVQLZs3l32LXZudHbUs_z1X
"""

import streamlit as st
import fitz  # PyMuPDF
import re
import zipfile
import io
import pandas as pd

st.set_page_config(page_title="PDF RO Renamer", page_icon="📄")

st.title("PDF RO Name Renamer")

st.write(
    "Upload one or more PDFs. The app will extract the RO Name and rename the files."
)

uploaded_files = st.file_uploader(
    "Upload PDFs",
    type="pdf",
    accept_multiple_files=True
)

def sanitize_filename(name):
    name = re.sub(r'[\\/*?:"<>|]', "", name)
    name = re.sub(r"\s+", "_", name.strip())
    return name

def extract_ro_name(text):
    pattern = r"RO Name\s+(.*?)\s+RO Type"
    match = re.search(pattern, text, re.DOTALL)

    if match:
        return match.group(1).strip()

    return None

if uploaded_files:

    zip_buffer = io.BytesIO()

    preview = []

    used_names = {}

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zipf:

        progress = st.progress(0)

        for i, pdf in enumerate(uploaded_files):

            doc = fitz.open(stream=pdf.read(), filetype="pdf")

            text = ""

            for page in doc:
                text += page.get_text()

            doc.close()

            ro_name = extract_ro_name(text)

            if ro_name:

                clean_name = sanitize_filename(ro_name)

                new_name = f"DDO_{clean_name}.pdf"

                if new_name in used_names:
                    used_names[new_name] += 1
                    new_name = f"DDO_{clean_name}_{used_names[new_name]}.pdf"
                else:
                    used_names[new_name] = 1

            else:
                new_name = f"ERROR_{pdf.name}"

            preview.append({
                "Old File": pdf.name,
                "New File": new_name
            })

            pdf.seek(0)
            zipf.writestr(new_name, pdf.read())

            progress.progress((i + 1) / len(uploaded_files))

    st.success("Processing Complete!")

    st.subheader("Preview")

    st.dataframe(pd.DataFrame(preview), use_container_width=True)

    st.download_button(
        label="Download ZIP",
        data=zip_buffer.getvalue(),
        file_name="Renamed_PDFs.zip",
        mime="application/zip"
    )